[package]
name = "rpautovpn"
version = "0.3.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.21"
pnet = "0.35.0"
simplelog = "0.12.2"
